on:
  push:
    branches:
      - main
      - master

name: increment-version

jobs:
  increment-version:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::usethis

      - name: Check if description has been updated
        shell: Rscript {0}
        run: |
          usethis::use_version("dev")
          pkg_ver <- package_version(read.dcf('DESCRIPTION', fields = 'Version')[[1]])
          Sys.setenv(PKG_VER = pkg_ver)
      - name: Setup Git User
        run: |
          git config --local user.name "Github Actions"
          git config --local user.email "github-actions@users.noreply.github.com"
          git pull

      - name: Commit and push
        run: |
          git add DESCRIPTION
          git commit -m "increment-package to $PKG_VER"
          git push origin
