on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]

name: increment-version

jobs:
  increment-version:
    runs-on: ubuntu-latest

    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      R_KEEP_PKG_SOURCE: yes

    steps:
      - uses: actions/checkout@v3
        with:
          ref: main
          path: main-clone

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: 'release'
          use-public-rspm: true

      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          extra-packages: any::usethis
          needs: use_package
      
      - name: Check where path goes
        shell: Rscript {0}
        run: |
          print(list.files(".."))
          path <- '${{ GITHUB.WORKSPACE }}'
          print(path)
          print(list.files(path, recursive = TRUE))

      - uses: actions/checkout@v3
      
      - name: Check if description has been updated
        shell: Rscript {0}
        run: |
          print(list.files(".."))
          pr_ver <- package_version(read.dcf('DESCRIPTION', fields = 'Version')[[1]])
          path <- '${{ GITHUB.WORKSPACE }}'
          print(path)
          print(list.files(path, recursive = TRUE))
          #cur_ver <- package_version(read.dcf(file.path("main-clone", 'DESCRIPTION'), fields = 'Version')[[1]])
          #if (pr_ver == cur_ver) stop("Need to increment!")
